### ISSUE TITLE
建议增加对controller的解析支持，增加个判断即可

### ISSUE THREAD

**Issue by qtvbwfn** [apiggs/apiggs#12]
![image](https://user-images.githubusercontent.com/5848026/47707235-4b208f00-dc66-11e8-936d-4466bc86bc4b.png)

如图

**Comment by ayz6uem** [comment]
这个地方是判断一个Controller是否ResponseBody的，增加这个逻辑就不对了

**Comment by qtvbwfn** [comment]
对于一个大型项目来说，肯定会统一个标准的出参格式，比如在intercepter中处理返回一个标准json
这个时候，并不会在controller上写上ResponseBody之类的注解，请求也不是restcontroller,而是普通的controller

**Comment by ayz6uem** [comment]
好的，感谢反馈，后期后考虑这种情况
