### ISSUE TITLE
asiidoc的关键字与注释模板冲突

### ISSUE THREAD

**Issue by eumji025** [apiggs/apiggs#9]
比如在asiidoc中  
```
*****************
aaaaaaaa
*****************
bbbbbbbb
*****************
```
这样的注释模板就是乱掉，可能需要转义一下，今天白天我也稍微看一下。
可以通过
```
++++
*****************
++++
```
这样的方式解决，不知道还有没有更优雅的方式，我不太懂asiidoc的规范

**Comment by ayz6uem** [comment]
感谢反馈，正在更换asciidoc生成工具，会注意到这一点

**Comment by eumji025** [comment]
好的，今天有时间我也会重新看看有没有什么好的方式解决

**Comment by ayz6uem** [comment]
/*****************
aaaaaaaa
 *****************
bbbbbbbb
 *****************

注释中可以有asciidoc的特殊字符，且会解析为asciidoc的文档效果，这样可以写成富文本的描述。
asciidoc的block特殊字符（****）必须顶头，所以前面加个空格就能防止asciidoc解析
如果特殊字符在第一行，那么可以加上一些其他字符，如 / | -等

**Comment by eumji025** [comment]
thank you
